stages:
  - build
  - docker-build
  - docker-push

variables:
  APP_NAME: $CI_PROJECT_NAME
  APP_BINARY: "${APP_NAME}App"
  IMAGE_NAME: alpeshjamgade/$APP_NAME:$CI_COMMIT_REF_NAME
  DOCKER_IMAGE: docker:20.10.22
  DOCKER_DIND_IMAGE: docker:dind

build:
  stage: build
  image: golang:1.22.0
  script:
    - go build -o _build/${APP_BINARY} main.go
    - ps aux

docker-build:
  stage: docker-build
  image: $DOCKER_IMAGE
  services:
    - name: $DOCKER_DIND_IMAGE
      alias: docker
  script:
    - docker build -f Dockerfile -t $IMAGE_NAME .
    - echo $IMAGE_NAME
  dependencies: ["build"]
  needs: ["build"]
  only:
    - tags

docker-push:
  stage: docker-push
  image: $DOCKER_IMAGE
  services:
    - name: $DOCKER_DIND_IMAGE
      alias: docker
  script:
    - docker push $IMAGE_NAME
    - echo $IMAGE_NAME
  only:
    - tags