services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shrink-link
    volumes:
      - ./_data/postgres_data:/var/lib/postgresql/data
      - ./_data/init/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  shrink-link:
    image: alpeshjamgade/shrink-link:release
    volumes:
      - "./config/prod-config.yaml:/etc/shrink-link/config.yaml"
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

