http_port: "1212"
redis_host: "localhost"
redis_port: "6379"
db_host: "localhost"
db_username: "postgres"
db_password: "postgres"
db_port: "5432"
db_name: "shrinklink"
domain: "http://localhost:1212"

log_level: "info"
log_encoding: "json"