name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build Go application
        run: |
          go build -o _build/${{ env.APP_BINARY }} main.go
          ps aux

    env:
      APP_NAME: ${{ github.repository }}
      APP_BINARY: '${{ env.APP_NAME }}App'

  docker-build:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ${{ env.IMAGE_NAME }} .
          echo ${{ env.IMAGE_NAME }}
        env:
          IMAGE_NAME: alpeshjamgade/${{ github.repository }}:${{ github.ref_name }}

  docker-push:
    runs-on: self-hosted
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}
          echo ${{ env.IMAGE_NAME }}
        env:
          IMAGE_NAME: alpeshjamgade/${{ github.repository }}:${{ github.ref_name }}
